CREATE TABLE IF NOT EXISTS preferences (
    character_id               INTEGER  NOT NULL,
    donation_rows              INTEGER  NOT NULL DEFAULT 5,
    contract_rows              INTEGER  NOT NULL DEFAULT 5,
    combined_rows              INTEGER  NOT NULL DEFAULT 5,
    donation_max_age           INTEGER  NOT NULL DEFAULT 0,
    contract_max_age           INTEGER  NOT NULL DEFAULT 0,
    combined_max_age           INTEGER  NOT NULL DEFAULT 0,
    donation_min               FLOAT    NOT NULL DEFAULT 0.1,
    contract_min               FLOAT    NOT NULL DEFAULT 0.1,
    combined_min_donation      FLOAT    NOT NULL DEFAULT 0.1,
    combined_min_contract      FLOAT    NOT NULL DEFAULT 0.1,
    donation_header            TEXT,
    donation_footer            TEXT,
    donation_pattern           TEXT,
    donation_passphrase        TEXT,
    contract_header            TEXT,
    contract_footer            TEXT,
    contract_pattern           TEXT,
    contract_passphrase        TEXT,
    combined_header            TEXT,
    combined_footer            TEXT,
    combined_donation_pattern  TEXT,
    combined_contract_pattern  TEXT,
    combined_passphrase        TEXT,
    PRIMARY KEY (character_id)
);
